### ISSUE TITLE
Initial focus

### ISSUE THREAD

**Issue by artouiros** [vganin/dpad-aware-recycler-view#1]
Any way to set initial focus on 0 itemview? When launchign the demo app I must press Down key to enable d-pad interaction and the 5th view get focused.

**Comment by vganin** [comment]
Hi!

I'm sorry, unfortunately RecyclerView lacks of such capability at the moment (at least not that I'm aware of) so do DpadAwareRecyclerView.

As a quick and dirty workaround you could use this snippet

``` java
list.getViewTreeObserver().addOnGlobalLayoutListener(
                new ViewTreeObserver.OnGlobalLayoutListener() {
                    @Override
                    public void onGlobalLayout() {
                        list.scrollToPosition(0);
                        list.getChildAt(0).requestFocus();

                        list.getViewTreeObserver().removeOnGlobalLayoutListener(this);
                    }
                });
```

I will look into adding such capability later. Thank you for the idea!

Best regards,
V

**Comment by vganin** [comment]
Hi!

I made a couple of changes recently including more fine-grained control over focus flow. It's still pretty raw though, but I think this issue must be solved for you.

Best regards,
V
